- part: vanilla options
  - section: (general)
    - Realms Notifications: ON -> OFF
  - section: Skin Customization
  - section: Video Settings
    - Brightness: Moody -> Bright
    - Clouds: Fancy -> Fast
  - section: Language
  - section: Resource Packs
  - section: Music & Sounds
    - Master Volume: 100% -> 80 %
    - Music: 100% -> 70 %
  - section: Controls
    - subsection: (general)
      - Auto-Jump: ON -> OFF
    - subsection: Movement
      - Sneak: Left Shift -> Left Control
      - Sprint: Left Control -> Left Shift
    - subsection: Gameplay
    - subsection: Inventory
      - Drop Selected Item: q -> g
    - subsection: Creative Mode
    - subsection: Multiplayer
    - subsection: Miscellaneous
      - Highlight Players (Spectators): Not bound -> k
      - Toggle Cinematic Camera: Not bound -> o
      - Toggle Perspective: F5 -> p
  - section: Chat Settings
    - Unfocused Height: 90px -> 50px
  - section: Accessibility Settings (1.14 only)
  - section: Snooper Settings
- part: additional options - Forge, Xaero’s Minimap, OptiFine
  same-as-vanilla:
    - "Skin Customization"
    - "Language"
    - "Resource Packs"
    - "Music & Sounds"
    - "Chat Settings"
    - "Snooper Settings"
  - section: Video Setting
    - subsection: (general)
      - Brightness: Moody -> Bright
      - Render Distance: 8 Normal -> 12 Normal+
    - subsection: Shaders
    - subsection: Details
      - Clouds: Default -> Fast
      - Vignette: Default -> Fast
    - subsection: Animations
    - subsection: Quality
    - subsection: Performance
    - subsection: Other
  - section: Controls
    same-as-vanilla:
      - "Movement"
      - "Gameplay"
      - "Inventory"
    - subsection: Creative Mode
      - Save Toolbar Activator: C [conflict] -> V
    - subsection: Multiplayer
    - subsection: Miscellaneous
      - Toggle Perspective: F5 -> P
      - Zoom: C [conflict]
    - subsection: Xaero’s Minimap
      - Enlarge Minimap: Z -> Y
      - Minimap Settings: Y -> Z
  - section: [ Xaero’s Minimap settings ]
    - subsection: [ page 1 ]
      - Minimap Size: Auto -> 125
      - Zoom: 3.0x -> 2.0x
      - Lock North: OFF -> ON
      - On-map Waypoints: ON -> OFF
      - In-game Waypoints: ON -> OFF
    - subsection: Entity Radar
      - Players: Aqua -> White/ON -> Green/ON
      - Other Teams: White -> Players/ON -> Aqua/ON
      - Friendly Mobs: Yellow/ON
      - Hostile Mobs: Yellow/ON -> Red/ON
      - Items: Green -> Red/ON -> Blue/ON
      - Other Entities: OFF -> DarkPurple/ON -> Purple/ON
    - subsection: [ page 2 ]
      - Keep Old Deathpoints: ON -> OFF
    - subsection: [ page 3 ]
      - Entity Height Limit: 20.0 -> 10.0
      - Lighting: ON -> OFF
      - Arrow Scale: 1.5x -> 1.4x
    - subsection: [ page 4 ]
      - Show Current Biome: OFF -> ON
    - subsection: [ page 5 ]

